### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Echel8n** [JarkoreDrake/Feednix#44]
I had installed feednix on my debian computer.

 `Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux`

When I launched feednix for the first time, I register my feedly User ID and my token.
When I launch feednix, I have an segmentation fault. 

Update : 

I launched gdb and I made a backtrace of the error: 

[http://pastebin.com/ASh8x10i](url)

And valgrind result : 
[http://pastebin.com/MjKYpJ7v](url)

**Comment by sublimino** [comment]
(just another user here) - are you on the dedicated Ubuntu/Debian branch? 

https://github.com/Jarkore/Feednix#update-for-ubuntu-and-fedora-users
